import Head from "next/head";
import Link from "next/link";
import { RestoCard } from "~/components/app/RestoCard";

import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.resto.getNearbyRestos.useQuery({ lng: -95.352944, lat: 29.774556, radius: 1500 });

  if (!data) {
    return <>Loading Card</>
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col m-4 items-center justify-center">
        {data.map((e) => <RestoCard place={e} />)}
      </main>
    </>
  );
}
